// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyznfUhFDdR653a-Kz6pWm6WfUmnPRXJ8',
    appId: '1:178956125719:ios:eff39260f8e40378443e52',
    messagingSenderId: '178956125719',
    projectId: 'fsspot-ae02c',
    storageBucket: 'fsspot-ae02c.firebasestorage.app',
    iosBundleId: 'com.fsspot.fsdelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTcby5xe3C3hrx6WNl2sQd9gNkNjJ3-eM',
    appId: '1:178956125719:web:fd734bb0076ca036443e52',
    messagingSenderId: '178956125719',
    projectId: 'fsspot-ae02c',
    authDomain: 'fsspot-ae02c.firebaseapp.com',
    storageBucket: 'fsspot-ae02c.firebasestorage.app',
    measurementId: 'G-9W7G48PR3Y',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTcby5xe3C3hrx6WNl2sQd9gNkNjJ3-eM',
    appId: '1:178956125719:web:fd734bb0076ca036443e52',
    messagingSenderId: '178956125719',
    projectId: 'fsspot-ae02c',
    authDomain: 'fsspot-ae02c.firebaseapp.com',
    storageBucket: 'fsspot-ae02c.firebasestorage.app',
    measurementId: 'G-9W7G48PR3Y',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyznfUhFDdR653a-Kz6pWm6WfUmnPRXJ8',
    appId: '1:178956125719:ios:eff39260f8e40378443e52',
    messagingSenderId: '178956125719',
    projectId: 'fsspot-ae02c',
    storageBucket: 'fsspot-ae02c.firebasestorage.app',
    iosBundleId: 'com.fsspot.fsdelivery',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuHNiCJemNxaen393oBBByyY_ERG8B_FU',
    appId: '1:178956125719:android:34b8481b41e48d21443e52',
    messagingSenderId: '178956125719',
    projectId: 'fsspot-ae02c',
    storageBucket: 'fsspot-ae02c.firebasestorage.app',
  );

}